/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package avioapp.view;

import avioapp.controller.ObradaLet;
import avioapp.model.Avion;
import avioapp.model.Let;
import avioapp.utility.Utility;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.function.Consumer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author PC
 */
public class FormaListaLetova extends javax.swing.JFrame {

    private ObradaLet obrada;

    /**
     * Creates new form FormaListaLetova
     */
    public FormaListaLetova() {
        initComponents();
        setTitle(Utility.getNazivAplikacije() + " " + " Lista letova ");
        setLocationRelativeTo(null);
        obrada = new ObradaLet();

        ucitaj();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLetovi = new javax.swing.JTable();
        btnunos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itmIzlaz = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Letovi"));

        tblLetovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(tblLetovi);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        btnunos.setText("Unos");
        btnunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnunosActionPerformed(evt);
            }
        });

        jMenu1.setText("Izbornik");

        itmIzlaz.setText("Izlaz");
        itmIzlaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmIzlazActionPerformed(evt);
            }
        });
        jMenu1.add(itmIzlaz);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnunos, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnunos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmIzlazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmIzlazActionPerformed
        dispose();
    }//GEN-LAST:event_itmIzlazActionPerformed

    private void btnunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnunosActionPerformed
        new FormaLetovi().setVisible(true);
    }//GEN-LAST:event_btnunosActionPerformed
    private void ucitaj() {
        SimpleDateFormat df = new SimpleDateFormat("dd. MM. yyyy.");
        DefaultTableModel dtm = (DefaultTableModel) tblLetovi.getModel();
        List<Let> letovi = obrada.getEntiteti();
        String[] colNames = {"Naziv leta", "Datum odlaska", "Datum dolaska", "Polazište", "Odredište"};
        for (int i = 0; i < colNames.length; i++) {

            TableColumn tc = tblLetovi.getColumnModel().getColumn(i);
            tc.setHeaderValue(colNames[i]);
        }
        letovi.forEach((l) -> {
            try {
                String red[] = {
                    l.getImeLeta(),
                    df.format(l.getDatumOdlaska()),
                    df.format(l.getDatumDolaska()),
                    l.getPolaziste(),
                    l.getOdrediste(),
                };

                dtm.addRow(red);

            } catch (Exception e) {

            }
        });            

    } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnunos;
    private javax.swing.JMenuItem itmIzlaz;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLetovi;
    // End of variables declaration//GEN-END:variables
}
